
development:
  adapter: postgresql
  encoding: unicode
  database: Sonifizer_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: Sonifizer_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: Sonifizer_production
  pool: 5
  host: localhost
